[package]
name = "analysis-performance-exponential-kernel"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../../../necsim/core", features = ["cuda"] }
necsim-core-bond = { path = "../../../../necsim/core/bond" }
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", branch = "main", features = [] }
necsim-impls-no-std = { path = "../../../../necsim/impls/no-std", features = ["cuda"] }
necsim-impls-cuda = { path = "../../../../necsim/impls/cuda" }
contracts = "0.6.3"
