[package]
name = "necsim-partitioning-threads"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.tyree@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }
necsim-impls-std = { path = "../../impls/std" }
necsim-partitioning-core = { path = "../../partitioning/core" }

contracts = "0.6.3"
thiserror = "1.0"
anyhow = "1.0"
serde = "1.0"
humantime-serde = "1.1"
bit-set = "0.5"
